# Generated by Django 5.0.2 on 2024-02-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
