# Generated by Django 5.0.2 on 2024-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_projects_audience_remove_projects_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backer",
            name="amount_pledged",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
