# Generated by Django 5.0.2 on 2024-02-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_creator_bio_projects_end_date_projects_start_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
