# Generated by Django 5.0.2 on 2024-03-24 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_backer_amount_pledged"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="backers",
            field=models.ManyToManyField(
                related_name="backed_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
