# Generated by Django 5.0.2 on 2024-02-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_projects_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="audience",
        ),
        migrations.AlterField(
            model_name="audience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.user"
            ),
        ),
        migrations.AlterField(
            model_name="creator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.user"
            ),
        ),
    ]
