# Generated by Django 5.0.2 on 2024-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_project_description_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.TextField(max_length=200),
        ),
    ]
