# Generated by Django 5.0.2 on 2024-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_project_description_alter_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("art", "Art"),
                    ("comics", "Comics"),
                    ("games", "Games"),
                    ("publishing", "Publishing"),
                ],
                default="tech",
                max_length=200,
            ),
        ),
    ]
