# Generated by Django 5.0.2 on 2024-03-02 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_project_project_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audience",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creator",
            name="user",
        ),
        migrations.AddField(
            model_name="audience",
            name="username",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="username",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="creator",
            name="bio",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
