# Generated by Django 5.0.2 on 2024-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_creator_fund_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="fund_collected",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
