# Generated by Django 5.0.2 on 2024-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_audience_user_remove_creator_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("technology", "Technology"),
                    ("art", "Art"),
                    ("comics", "Comics"),
                    ("games", "Games"),
                    ("publishing", "Publishing"),
                ],
                default="technology",
                max_length=200,
            ),
        ),
    ]
