# Generated by Django 5.0.2 on 2024-03-18 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_project_project_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="backers",
            field=models.ManyToManyField(
                blank=True, related_name="backed_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
