# Generated by Django 5.0.2 on 2024-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_creator_fund_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="fund_collected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
