# Generated by Django 5.0.2 on 2024-05-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_creator_fund_collected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="backers",
        ),
    ]
