# Generated by Django 5.0.2 on 2024-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_project_backers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rewards",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
